# -*- mode:ruby -*-

require 'maven/ruby/tasks'

include Maven::Tools::DSL

# test tasks are renamed due to tasks caching and conflict with 
# simple and simple_fail tests

task :maven2 do
  maven do
    gemspec
    jarfile
    scope :test do
      jar 'junit:junit', '4.11'
    end
  end
end

task :test => [:maven2, :junit] do 
  require 'minitest'
  require 'minitest/autorun'
  require './spec/my_spec.rb'
end

task :build2 => :maven2 do
  maven.package( '-Dmaven.test.skip' )
end

task :clean2 => :maven2 do
  maven.clean
end

# vim: syntax=Ruby
