# -*- mode:ruby -*-

require 'maven/ruby/tasks'

task :default => :test

task :test do
  begin
    require 'minitest'
  rescue LoadError
  end
  require 'minitest/autorun'
  require './spec/simple_spec.rb'
  require './spec/with_jars_spec.rb'
end

# vim: syntax=Ruby
